In [ ]:
#Section A: Data Structures & Control Structures

In [1]:
# 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [2]:
list= [10,20,30,40,50]

In [3]:
type(list)

list

In [4]:
list.append(60)

In [5]:
list

[10, 20, 30, 40, 50, 60]

In [6]:
a=[70,80]

In [7]:
list.extend(a)

In [8]:
list

[10, 20, 30, 40, 50, 60, 70, 80]

In [9]:
list.insert(3,25)

In [10]:
list

[10, 20, 30, 25, 40, 50, 60, 70, 80]

In [11]:
list.remove(60)

In [12]:
list

[10, 20, 30, 25, 40, 50, 70, 80]

In [13]:
list.pop(7)

80

In [14]:
list

[10, 20, 30, 25, 40, 50, 70]

In [15]:
list.reverse()

In [16]:
list

[70, 50, 40, 25, 30, 20, 10]

In [18]:
len(list)

7

In [19]:
list[3] #index

25

In [20]:
list.sort()

In [21]:
list

[10, 20, 25, 30, 40, 50, 70]

In [22]:
list.clear()

In [23]:
list

[]

In [24]:
len(list)

0

In [ ]:
# 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [25]:
t=("Ravi","Raju","Reena")

In [26]:
type(t)

tuple

In [27]:
t[2]

'Reena'

In [28]:
t[2]="Ramya"

TypeError: 'tuple' object does not support item assignment

In [29]:
# we can not replace the value or string in tuple because it is immutable

In [ ]:
#4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [75]:
d={"Name":'Ravi',"Age":25,"City":'Vijayawada' }

In [76]:
type(d)

dict

In [86]:
d.update({"E-mail": "ravi@gmail.com"})

In [87]:
d

{'Name': 'Ravi', 'Age': 25, 'City': 'Vijayawada', 'E-mail': 'ravi@gmail.com'}

In [ ]:
#5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [92]:
age=23

In [93]:
if age>=18:
    print("He is eligible for voting")
else:
    print("He is not eligible for voting")

He is eligible for voting


In [ ]:
#6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [115]:
marks=82

In [116]:
if marks>=90:
    print("Grade is A")
elif marks>=75 and marks<=89:
    print("Grade is B")
elif marks>=50 and marks<=74:
    print("Grade is C")
else:
    print("Fail")

Grade is B


In [ ]:
#7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative

In [128]:
x=26

In [129]:
if x>0:
    if x%2==0:
        print("x is even")
    else:
        print("x is odd")
    print("x is positive")
else:
    print("x is negative")

x is even
x is positive


In [ ]:
#3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [130]:
soi={101,102,103,106,102,105,103}

In [131]:
soi

{101, 102, 103, 105, 106}

In [ ]:
# here in set soi the values are sorting and duplicate values are removed.

In [ ]:
#Section B: Numpy

In [ ]:
#8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [3]:
import numpy as np

In [4]:
np.array([5])

array([5])

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
d1=np.arange(10,61,10)

In [7]:
d1

array([10, 20, 30, 40, 50, 60])

In [8]:
d1.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [9]:
#9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [10]:
np.random.randint(2,101,size=(4,4))

array([[97, 49, 36, 19],
       [81, 98, 46, 66],
       [18, 50, 41, 21],
       [51,  8, 85, 28]], dtype=int32)

In [11]:
#10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [12]:
d2= np.random.randint(10,50,size=(3,3))

In [13]:
import pandas as pd

In [14]:
d3= pd.DataFrame(d2)

In [15]:
d3.columns= ['A','B','C']

In [16]:
d3

A   B   C
0  26  48  41
1  14  44  27
2  46  44  43

In [17]:
#Section C: Exploring Pandas

In [52]:
#11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
"""
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows
"""

"\n- Use .info(), .describe()\n- Select 'Name' and 'City' columns\n- Drop 'City' column\n- Fill any missing values in 'Salary' column with the mean\n- Remove any duplicate rows\n"

In [19]:
data= {
    "Name":['Ravi','Reena','Pandu','Balu','Madhu','Meena','Teena','Balu','Bhanu','Seetha'],
    "Age":[23,21,31,24,42,32,29,24,19,21],
    "City":['HYD','Banglore','Chennai','Delhi','Raipur','Hyd','Banglore','Delhi','Jaipur','Delhi'],
    "Salary":[25000,30000,10000,50000,23000,21000,61000,00,31000,21000]
}


In [20]:
data

{'Name': ['Ravi',
  'Reena',
  'Pandu',
  'Balu',
  'Madhu',
  'Meena',
  'Teena',
  'Balu',
  'Bhanu',
  'Seetha'],
 'Age': [23, 21, 31, 24, 42, 32, 29, 24, 19, 21],
 'City': ['HYD',
  'Banglore',
  'Chennai',
  'Delhi',
  'Raipur',
  'Hyd',
  'Banglore',
  'Delhi',
  'Jaipur',
  'Delhi'],
 'Salary': [25000, 30000, 10000, 50000, 23000, 21000, 61000, 0, 31000, 21000]}

In [21]:
 df= pd.DataFrame(data)

In [22]:
df

Name  Age      City  Salary
0    Ravi   23       HYD   25000
1   Reena   21  Banglore   30000
2   Pandu   31   Chennai   10000
3    Balu   24     Delhi   50000
4   Madhu   42    Raipur   23000
5   Meena   32       Hyd   21000
6   Teena   29  Banglore   61000
7    Balu   24     Delhi       0
8   Bhanu   19    Jaipur   31000
9  Seetha   21     Delhi   21000

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [24]:
df.describe()

Age        Salary
count  10.000000     10.000000
mean   26.600000  27200.000000
std     6.979335  17699.968613
min    19.000000      0.000000
25%    21.500000  21000.000000
50%    24.000000  24000.000000
75%    30.500000  30750.000000
max    42.000000  61000.000000

In [25]:
df[df.columns[[0,2]]]

Name      City
0    Ravi       HYD
1   Reena  Banglore
2   Pandu   Chennai
3    Balu     Delhi
4   Madhu    Raipur
5   Meena       Hyd
6   Teena  Banglore
7    Balu     Delhi
8   Bhanu    Jaipur
9  Seetha     Delhi

In [26]:
df

Name  Age      City  Salary
0    Ravi   23       HYD   25000
1   Reena   21  Banglore   30000
2   Pandu   31   Chennai   10000
3    Balu   24     Delhi   50000
4   Madhu   42    Raipur   23000
5   Meena   32       Hyd   21000
6   Teena   29  Banglore   61000
7    Balu   24     Delhi       0
8   Bhanu   19    Jaipur   31000
9  Seetha   21     Delhi   21000

In [27]:
df1= df.drop('City',axis=1)

In [28]:
df1

Name  Age  Salary
0    Ravi   23   25000
1   Reena   21   30000
2   Pandu   31   10000
3    Balu   24   50000
4   Madhu   42   23000
5   Meena   32   21000
6   Teena   29   61000
7    Balu   24       0
8   Bhanu   19   31000
9  Seetha   21   21000

In [29]:
mean= np.round(df1['Salary'].mean())

In [30]:
df1[df1['Salary']==0]

Name  Age  Salary
7  Balu   24       0

In [31]:
df1['Salary'][df1['Salary']==0]=mean

C:\Users\andeb\AppData\Local\Temp\ipykernel_13816\2076554693.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['Salary'][df1['Salary']==0]=mean
C:\Users\andeb\AppData\Local\Temp\ipykernel_13816\2076554693.py:1: SettingWithCopyWarning: 

In [32]:
df1

Name  Age  Salary
0    Ravi   23   25000
1   Reena   21   30000
2   Pandu   31   10000
3    Balu   24   50000
4   Madhu   42   23000
5   Meena   32   21000
6   Teena   29   61000
7    Balu   24   27200
8   Bhanu   19   31000
9  Seetha   21   21000

In [45]:
import pandas as pd

In [49]:
df1.drop_duplicates(subset='Name',keep= 'first',inplace=True)

In [50]:
df1

Name  Age  Salary
0    Ravi   23   25000
1   Reena   21   30000
2   Pandu   31   10000
3    Balu   24   50000
4   Madhu   42   23000
5   Meena   32   21000
6   Teena   29   61000
8   Bhanu   19   31000
9  Seetha   21   21000